#deployment.yaml
#namespace: devops
replicaCount: 2
image:
  repository: 149536470392.dkr.ecr.us-east-2.amazonaws.com/application/repo
  tag: latest
containerPort: 80
# service.yaml
service:
  port: 80
  targetPort: 80
  containerPort: 80
  nodePort: 30008
  type: ClusterIP
